//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 2:42:05 PM on Thursday, April 19, 2001
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"ARC4 Library"
//
//	Palm App Version: 		"0.1"



//	Resource: tFRM 1000
#define UntitledForm                              1000

